# Generated by Django 5.2.5 on 2025-08-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=100)),
                ('frecuencia', models.IntegerField()),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='analisis.textoanalizado')),
            ],
        ),
    ]
