# Generated by Django 5.2.6 on 2025-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0002_palabra"),
    ]

    operations = [
        migrations.AddField(
            model_name="textoanalizado",
            name="nube_imagen",
            field=models.ImageField(blank=True, null=True, upload_to="wordclouds/"),
        ),
        migrations.AddField(
            model_name="textoanalizado",
            name="tokens_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
