# Generated by Django 5.2.6 on 2025-09-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0003_textoanalizado_nube_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textoanalizado",
            name="calcular_probabilidades",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textoanalizado",
            name="tipo_ngram",
            field=models.IntegerField(default=2),
        ),
    ]
